{
 "title": "ABSOLUTE STABLE MONITORING V11",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "SRE STATUS: PODS REACHABLE",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sum(up{app='node-k8s-app'})", "legendFormat": "Healthy Pods" }
   ]
  },
  {
   "title": "TRAFFIC: TOTAL RPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{app='node-k8s-app'}[5m]))",
     "legendFormat": "RPS"
    }
   ]
  },
  {
   "title": "ERRORS: 5XX RATE (%)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 5 },
   "targets": [
    {
     "expr": "(sum(rate(http_requests_total{status=~'5.*', app='node-k8s-app'}[5m])) or vector(0)) / (sum(rate(http_requests_total{app='node-k8s-app'}[5m])) or vector(1)) * 100"
    }
   ]
  },
  {
   "title": "RESOURCES: MEMORY (BYTES)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 5 },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{app='node-k8s-app'}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}